### ISSUE TITLE
Cambiar el color de la descripcion de la empresa , usar el colore negro

### ISSUE THREAD

**Issue by adminAgenciaServitec** [AgenciaServitec/eces-landing#14]
<img width="1468" alt="Screenshot 2024-06-07 at 12 37 43 PM" src="https://github.com/AgenciaServitec/eces-landing/assets/104750139/08783e06-b13b-41cf-8de3-f4e771c1d169">

**Comment by Ignacio2906** [comment]
![image](https://github.com/AgenciaServitec/eces-landing/assets/145935490/063bb664-75e1-4346-b7cf-964539f26a50)
